package protectedresource

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/maxvanp/terraform-provider-graviteeam/internal/client"
)

var (
	_ resource.Resource                = &ProtectedResourceResource{}
	_ resource.ResourceWithImportState = &ProtectedResourceResource{}
)

type ProtectedResourceResource struct {
	client *client.Client
}

func NewProtectedResourceResource() resource.Resource {
	return &ProtectedResourceResource{}
}

func (r *ProtectedResourceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_protected_resource"
}

func (r *ProtectedResourceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Gravitee AM Protected Resource",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the protected resource",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"domain_id": schema.StringAttribute{
				Required:    true,
				Description: "The ID of the domain this protected resource belongs to",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the protected resource",
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "The description of the protected resource",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "The protected resource type (for example, MCP_SERVER)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"resource_identifiers": schema.SetAttribute{
				Required:    true,
				ElementType: types.StringType,
				Description: "Set of resource identifiers protected by this resource",
			},
			"settings_json": schema.StringAttribute{
				Optional:    true,
				Description: "JSON object for advanced protected resource settings. The value is sent as the Gravitee AM settings payload.",
			},
			"client_id": schema.StringAttribute{
				Computed:    true,
				Description: "The OAuth2 client ID generated by Gravitee AM",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"client_secret": schema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "The OAuth2 client secret generated by Gravitee AM. Gravitee AM only returns the clear value at creation time.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"feature": schema.ListNestedBlock{
				Description: "Protected resource feature, such as an MCP tool definition",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Required:    true,
							Description: "The feature key",
						},
						"type": schema.StringAttribute{
							Required:    true,
							Description: "The feature type (for example, MCP_TOOL)",
						},
						"description": schema.StringAttribute{
							Optional:    true,
							Description: "The feature description",
						},
						"scopes": schema.SetAttribute{
							Optional:    true,
							ElementType: types.StringType,
							Description: "OAuth2 scopes required by this feature",
						},
					},
				},
			},
		},
	}
}

func (r *ProtectedResourceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *client.Client")
		return
	}
	r.client = c
}

func (r *ProtectedResourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ProtectedResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, err := r.buildCreateBody(plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid protected resource configuration", err.Error())
		return
	}

	result, err := r.client.CreateProtectedResource(ctx, plan.DomainID.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating protected resource", err.Error())
		return
	}

	r.readSecretIntoModel(&plan, result)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ProtectedResourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ProtectedResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.GetProtectedResource(ctx, state.DomainID.ValueString(), state.ID.ValueString(), state.Type.ValueString())
	if err != nil {
		if strings.Contains(err.Error(), "404") {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading protected resource", err.Error())
		return
	}

	savedSecret := state.ClientSecret
	savedSettingsJSON := state.SettingsJSON
	r.readIntoModel(&state, result)
	state.ClientSecret = savedSecret
	state.SettingsJSON = savedSettingsJSON
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ProtectedResourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ProtectedResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state ProtectedResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.ID = state.ID
	plan.ClientSecret = state.ClientSecret

	body, err := r.buildUpdateBody(plan, &state)
	if err != nil {
		resp.Diagnostics.AddError("Invalid protected resource configuration", err.Error())
		return
	}

	result, err := r.client.UpdateProtectedResource(ctx, plan.DomainID.ValueString(), plan.ID.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating protected resource", err.Error())
		return
	}

	savedSettingsJSON := plan.SettingsJSON
	r.readIntoModel(&plan, result)
	plan.ClientSecret = state.ClientSecret
	plan.SettingsJSON = savedSettingsJSON
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ProtectedResourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ProtectedResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteProtectedResource(ctx, state.DomainID.ValueString(), state.ID.ValueString(), state.Type.ValueString())
	if err != nil && !strings.Contains(err.Error(), "404") {
		resp.Diagnostics.AddError("Error deleting protected resource", err.Error())
	}
}

func (r *ProtectedResourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected format: domain_id/protected_resource_id, got: %s", req.ID))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("domain_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[1])...)
}

func (r *ProtectedResourceResource) buildCreateBody(plan ProtectedResourceModel) (map[string]interface{}, error) {
	body, err := r.buildUpdateBody(plan, nil)
	if err != nil {
		return nil, err
	}
	body["type"] = plan.Type.ValueString()
	return body, nil
}

func (r *ProtectedResourceResource) buildUpdateBody(plan ProtectedResourceModel, state *ProtectedResourceModel) (map[string]interface{}, error) {
	body := map[string]interface{}{
		"name":                plan.Name.ValueString(),
		"resourceIdentifiers": toStringValues(plan.ResourceIdentifiers),
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		body["description"] = plan.Description.ValueString()
	}

	if plan.Features != nil {
		body["features"] = featuresToAPI(plan.Features)
	} else if state != nil && state.Features != nil {
		body["features"] = []map[string]interface{}{}
	}

	settings, ok, err := settingsJSONToAPI(plan.SettingsJSON)
	if err != nil {
		return nil, err
	}
	if ok {
		body["settings"] = settings
	} else if state != nil && !state.SettingsJSON.IsNull() && !state.SettingsJSON.IsUnknown() {
		body["settings"] = map[string]interface{}{}
	}

	return body, nil
}

func (r *ProtectedResourceResource) readSecretIntoModel(model *ProtectedResourceModel, data map[string]interface{}) {
	if id, ok := data["id"].(string); ok {
		model.ID = types.StringValue(id)
	}
	if clientID, ok := data["clientId"].(string); ok {
		model.ClientID = types.StringValue(clientID)
	}
	if clientSecret, ok := data["clientSecret"].(string); ok {
		model.ClientSecret = types.StringValue(clientSecret)
	}
}

func (r *ProtectedResourceResource) readIntoModel(model *ProtectedResourceModel, data map[string]interface{}) {
	if id, ok := data["id"].(string); ok {
		model.ID = types.StringValue(id)
	}
	if name, ok := data["name"].(string); ok {
		model.Name = types.StringValue(name)
	}
	if description, ok := data["description"].(string); ok {
		model.Description = types.StringValue(description)
	}
	if resourceType, ok := data["type"].(string); ok {
		model.Type = types.StringValue(strings.ToUpper(resourceType))
	}
	if clientID, ok := data["clientId"].(string); ok {
		model.ClientID = types.StringValue(clientID)
	}
	if identifiers, ok := data["resourceIdentifiers"].([]interface{}); ok {
		model.ResourceIdentifiers = interfacesToStringValues(identifiers)
	}
	if features, ok := data["features"].([]interface{}); ok {
		model.Features = featuresFromAPI(features)
	}
}

func settingsJSONToAPI(value types.String) (map[string]interface{}, bool, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, false, nil
	}

	var settings map[string]interface{}
	if err := json.Unmarshal([]byte(value.ValueString()), &settings); err != nil {
		return nil, false, fmt.Errorf("settings_json must be a valid JSON object: %w", err)
	}
	return settings, true, nil
}

func featuresToAPI(features []ProtectedResourceFeatureModel) []map[string]interface{} {
	result := make([]map[string]interface{}, len(features))
	for i, feature := range features {
		entry := map[string]interface{}{
			"key":  feature.Key.ValueString(),
			"type": feature.Type.ValueString(),
		}
		if !feature.Description.IsNull() && !feature.Description.IsUnknown() {
			entry["description"] = feature.Description.ValueString()
		}
		if feature.Scopes != nil {
			entry["scopes"] = toStringValues(feature.Scopes)
		}
		result[i] = entry
	}
	return result
}

func featuresFromAPI(features []interface{}) []ProtectedResourceFeatureModel {
	result := make([]ProtectedResourceFeatureModel, 0, len(features))
	for _, feature := range features {
		featureMap, ok := feature.(map[string]interface{})
		if !ok {
			continue
		}

		model := ProtectedResourceFeatureModel{}
		if key, ok := featureMap["key"].(string); ok {
			model.Key = types.StringValue(key)
		}
		if featureType, ok := featureMap["type"].(string); ok {
			model.Type = types.StringValue(strings.ToUpper(featureType))
		}
		if description, ok := featureMap["description"].(string); ok {
			model.Description = types.StringValue(description)
		}
		if scopes, ok := featureMap["scopes"].([]interface{}); ok {
			model.Scopes = interfacesToStringValues(scopes)
		}
		result = append(result, model)
	}
	return result
}

func toStringValues(values []types.String) []string {
	result := make([]string, len(values))
	for i, value := range values {
		result[i] = value.ValueString()
	}
	return result
}

func interfacesToStringValues(values []interface{}) []types.String {
	result := make([]types.String, 0, len(values))
	for _, value := range values {
		if stringValue, ok := value.(string); ok {
			result = append(result, types.StringValue(stringValue))
		}
	}
	return result
}
