package application

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/maxvanp/terraform-provider-graviteeam/internal/client"
)

var (
	_ resource.Resource                = &ApplicationResource{}
	_ resource.ResourceWithImportState = &ApplicationResource{}
)

type ApplicationResource struct {
	client *client.Client
}

func NewApplicationResource() resource.Resource {
	return &ApplicationResource{}
}

func (r *ApplicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (r *ApplicationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Gravitee AM Application",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the application",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"domain_id": schema.StringAttribute{
				Required:    true,
				Description: "The ID of the domain this application belongs to",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the application",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "The type of the application (WEB, NATIVE, BROWSER, SERVICE, RESOURCE_SERVER)",
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "The description of the application",
			},
			"client_id": schema.StringAttribute{
				Computed:    true,
				Description: "The OAuth2 client ID (auto-generated by Gravitee AM)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"client_secret": schema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "The OAuth2 client secret (auto-generated by Gravitee AM)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"metadata_json": schema.StringAttribute{
				Optional:    true,
				Description: "JSON object for application metadata. Object values are sent to the Gravitee AM metadata payload.",
			},
			"settings_json": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "JSON object for advanced application settings. The value is merged into the Gravitee AM settings payload; typed blocks such as oauth_settings and mfa_settings override matching keys.",
			},
			"identity_providers": schema.ListAttribute{
				Optional:    true,
				Description: "List of identity provider IDs to associate with the application",
				ElementType: types.StringType,
			},
			"factors": schema.ListAttribute{
				Optional:    true,
				Description: "List of MFA factor IDs to associate with the application",
				ElementType: types.StringType,
			},
		},
		Blocks: map[string]schema.Block{
			"identity_provider_rule": schema.ListNestedBlock{
				Description: "Identity provider with selection rule for identifier-first login routing",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"identity": schema.StringAttribute{
							Required:    true,
							Description: "The identity provider ID",
						},
						"selection_rule": schema.StringAttribute{
							Optional:    true,
							Description: "EL expression for routing (e.g. {#request.params['username'][0].endsWith('@example.com')})",
						},
						"priority": schema.Int64Attribute{
							Required:    true,
							Description: "Priority order (lower = higher priority)",
						},
					},
				},
			},
			"oauth_settings": schema.SingleNestedBlock{
				Description: "OAuth2/OIDC settings",
				Attributes: map[string]schema.Attribute{
					"redirect_uris": schema.ListAttribute{
						Optional:    true,
						Description: "Allowed redirect URIs",
						ElementType: types.StringType,
					},
					"post_logout_redirect_uris": schema.ListAttribute{
						Optional:    true,
						Description: "Allowed post-logout redirect URIs",
						ElementType: types.StringType,
					},
					"grant_types": schema.ListAttribute{
						Optional:    true,
						Description: "Allowed grant types",
						ElementType: types.StringType,
					},
					"response_types": schema.ListAttribute{
						Optional:    true,
						Description: "Allowed response types",
						ElementType: types.StringType,
					},
					"scopes": schema.ListAttribute{
						Optional:    true,
						Description: "Allowed OAuth2/OIDC scopes (e.g. openid, profile, email)",
						ElementType: types.StringType,
					},
					"access_token_validity_seconds": schema.Int64Attribute{
						Optional:    true,
						Computed:    true,
						Description: "Access token lifetime in seconds",
					},
					"refresh_token_validity_seconds": schema.Int64Attribute{
						Optional:    true,
						Computed:    true,
						Description: "Refresh token lifetime in seconds",
					},
					"id_token_validity_seconds": schema.Int64Attribute{
						Optional:    true,
						Computed:    true,
						Description: "ID token lifetime in seconds",
					},
				},
			},
			"mfa_settings": schema.SingleNestedBlock{
				Description: "MFA settings",
				Attributes: map[string]schema.Attribute{
					"enrollment": schema.StringAttribute{
						Optional:    true,
						Description: "MFA enrollment type: OPTIONAL, REQUIRED, or CONDITIONAL",
					},
					"challenge": schema.StringAttribute{
						Optional:    true,
						Description: "MFA challenge type: OPTIONAL, REQUIRED, or CONDITIONAL",
					},
				},
			},
		},
	}
}

func (r *ApplicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *client.Client")
		return
	}
	r.client = c
}

func (r *ApplicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateBody, err := r.buildUpdateBody(plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid application configuration", err.Error())
		return
	}

	createBody, err := r.buildCreateBody(plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid application configuration", err.Error())
		return
	}

	result, err := r.client.CreateApplication(ctx, plan.DomainID.ValueString(), createBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating application", err.Error())
		return
	}

	id := result["id"].(string)
	plan.ID = types.StringValue(id)

	// Capture client_id and client_secret from creation response (only time we get the real secret)
	r.readCredentials(&plan, result)
	savedSecret := plan.ClientSecret

	current, err := r.client.GetApplication(ctx, plan.DomainID.ValueString(), id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading application before post-create update", err.Error())
		return
	}

	// Step 2: Update with full config (identity providers, factors, settings)
	result, err = r.client.UpdateApplication(ctx, plan.DomainID.ValueString(), id, mergeApplicationUpdateBody(current, updateBody))
	if err != nil {
		resp.Diagnostics.AddError("Error updating application after creation", err.Error())
		return
	}

	// Refresh full state from API response
	r.readIntoModel(&plan, result)
	// Restore client_secret from create response (API masks it with ******** on PUT)
	plan.ClientSecret = savedSecret
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.GetApplication(ctx, state.DomainID.ValueString(), state.ID.ValueString())
	if err != nil {
		if strings.Contains(err.Error(), "404") {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading application", err.Error())
		return
	}

	r.readIntoModel(&state, result)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.ID = state.ID
	plan.ClientSecret = state.ClientSecret

	updateBody, err := r.buildUpdateBody(plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid application configuration", err.Error())
		return
	}

	current, err := r.client.GetApplication(ctx, plan.DomainID.ValueString(), plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading application before update", err.Error())
		return
	}

	result, err := r.client.UpdateApplication(ctx, plan.DomainID.ValueString(), plan.ID.ValueString(), mergeApplicationUpdateBody(current, updateBody))
	if err != nil {
		resp.Diagnostics.AddError("Error updating application", err.Error())
		return
	}

	if !plan.Type.Equal(state.Type) {
		result, err = r.client.UpdateApplicationType(ctx, plan.DomainID.ValueString(), plan.ID.ValueString(), plan.Type.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Error updating application type", err.Error())
			return
		}
	}

	// Refresh full state from API response
	r.readIntoModel(&plan, result)
	// Preserve client_secret from state (API masks it with ******** on PUT)
	plan.ClientSecret = state.ClientSecret
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteApplication(ctx, state.DomainID.ValueString(), state.ID.ValueString())
	if err != nil {
		if strings.Contains(err.Error(), "404") {
			return
		}
		resp.Diagnostics.AddError("Error deleting application", err.Error())
	}
}

func (r *ApplicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import format: domain_id/application_id
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected format: domain_id/application_id, got: %s", req.ID))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("domain_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[1])...)
}

func (r *ApplicationResource) buildCreateBody(plan ApplicationModel) (map[string]interface{}, error) {
	body := map[string]interface{}{
		"name": plan.Name.ValueString(),
		"type": plan.Type.ValueString(),
	}

	if !plan.Description.IsNull() {
		body["description"] = plan.Description.ValueString()
	}

	metadata, metadataProvided, err := metadataJSONToAPI(plan.MetadataJSON)
	if err != nil {
		return nil, err
	}
	if metadataProvided {
		body["metadata"] = metadata
	}

	redirectURIs, err := redirectURIsForCreate(plan)
	if err != nil {
		return nil, err
	}
	if len(redirectURIs) > 0 {
		body["redirectUris"] = redirectURIs
	}

	return body, nil
}

func (r *ApplicationResource) buildUpdateBody(plan ApplicationModel) (map[string]interface{}, error) {
	body := map[string]interface{}{
		"name": plan.Name.ValueString(),
		// DO NOT include "type" in update - it's only valid at creation
	}

	if !plan.Description.IsNull() {
		body["description"] = plan.Description.ValueString()
	}

	metadata, metadataProvided, err := metadataJSONToAPI(plan.MetadataJSON)
	if err != nil {
		return nil, err
	}
	if metadataProvided {
		body["metadata"] = metadata
	}

	// Identity providers - prefer identity_provider_rule blocks over simple list
	if len(plan.IdentityProviderRules) > 0 {
		idps := make([]map[string]interface{}, len(plan.IdentityProviderRules))
		for i, rule := range plan.IdentityProviderRules {
			entry := map[string]interface{}{
				"identity": rule.Identity.ValueString(),
				"priority": int(rule.Priority.ValueInt64()),
			}
			if !rule.SelectionRule.IsNull() && !rule.SelectionRule.IsUnknown() {
				entry["selectionRule"] = rule.SelectionRule.ValueString()
			}
			idps[i] = entry
		}
		body["identityProviders"] = idps
	} else if plan.IdentityProviders != nil {
		idps := make([]map[string]interface{}, len(plan.IdentityProviders))
		for i, idp := range plan.IdentityProviders {
			idps[i] = map[string]interface{}{
				"identity": idp.ValueString(),
				"priority": i,
			}
		}
		body["identityProviders"] = idps
	}

	// Factors
	if plan.Factors != nil {
		factors := make([]string, len(plan.Factors))
		for i, f := range plan.Factors {
			factors[i] = f.ValueString()
		}
		body["factors"] = factors
	}

	// Settings
	settings, settingsProvided, err := settingsJSONToAPI(plan.SettingsJSON)
	if err != nil {
		return nil, err
	}
	if settings == nil {
		settings = map[string]interface{}{}
	}

	// OAuth settings
	if plan.OAuthSettings != nil {
		oauth := map[string]interface{}{}
		if plan.OAuthSettings.RedirectURIs != nil {
			uris := make([]string, len(plan.OAuthSettings.RedirectURIs))
			for i, u := range plan.OAuthSettings.RedirectURIs {
				uris[i] = u.ValueString()
			}
			oauth["redirectUris"] = uris
		}
		if plan.OAuthSettings.PostLogoutRedirectURIs != nil {
			uris := make([]string, len(plan.OAuthSettings.PostLogoutRedirectURIs))
			for i, u := range plan.OAuthSettings.PostLogoutRedirectURIs {
				uris[i] = u.ValueString()
			}
			oauth["postLogoutRedirectUris"] = uris
		}
		if plan.OAuthSettings.GrantTypes != nil {
			gts := make([]string, len(plan.OAuthSettings.GrantTypes))
			for i, g := range plan.OAuthSettings.GrantTypes {
				gts[i] = g.ValueString()
			}
			oauth["grantTypes"] = gts
		}
		if plan.OAuthSettings.ResponseTypes != nil {
			rts := make([]string, len(plan.OAuthSettings.ResponseTypes))
			for i, rt := range plan.OAuthSettings.ResponseTypes {
				rts[i] = rt.ValueString()
			}
			oauth["responseTypes"] = rts
		}
		if plan.OAuthSettings.Scopes != nil {
			scopes := make([]map[string]interface{}, len(plan.OAuthSettings.Scopes))
			for i, s := range plan.OAuthSettings.Scopes {
				scopes[i] = map[string]interface{}{
					"scope":        s.ValueString(),
					"defaultScope": true,
				}
			}
			oauth["scopeSettings"] = scopes
		}
		if !plan.OAuthSettings.AccessTokenValiditySeconds.IsNull() && !plan.OAuthSettings.AccessTokenValiditySeconds.IsUnknown() {
			oauth["accessTokenValiditySeconds"] = plan.OAuthSettings.AccessTokenValiditySeconds.ValueInt64()
		}
		if !plan.OAuthSettings.RefreshTokenValiditySeconds.IsNull() && !plan.OAuthSettings.RefreshTokenValiditySeconds.IsUnknown() {
			oauth["refreshTokenValiditySeconds"] = plan.OAuthSettings.RefreshTokenValiditySeconds.ValueInt64()
		}
		if !plan.OAuthSettings.IDTokenValiditySeconds.IsNull() && !plan.OAuthSettings.IDTokenValiditySeconds.IsUnknown() {
			oauth["idTokenValiditySeconds"] = plan.OAuthSettings.IDTokenValiditySeconds.ValueInt64()
		}
		mergeSettingsSection(settings, "oauth", oauth)
	}

	// MFA settings
	if plan.MFASettings != nil {
		mfa := map[string]interface{}{}

		if len(plan.Factors) > 0 {
			// Build application factors list
			appFactors := make([]map[string]interface{}, len(plan.Factors))
			for i, f := range plan.Factors {
				appFactors[i] = map[string]interface{}{
					"id":            f.ValueString(),
					"selectionRule": "",
				}
			}
			mfa["factor"] = map[string]interface{}{
				"defaultFactorId":    plan.Factors[0].ValueString(),
				"applicationFactors": appFactors,
			}
		}

		if !plan.MFASettings.Enrollment.IsNull() {
			enrollType := plan.MFASettings.Enrollment.ValueString()
			mfa["enroll"] = map[string]interface{}{
				"active":          true,
				"forceEnrollment": enrollType == "REQUIRED",
				"type":            enrollType,
			}
		}

		if !plan.MFASettings.Challenge.IsNull() {
			challengeType := plan.MFASettings.Challenge.ValueString()
			mfa["challenge"] = map[string]interface{}{
				"active": true,
				"type":   challengeType,
			}
		}

		mergeSettingsSection(settings, "mfa", mfa)
	}

	if settingsProvided || len(settings) > 0 {
		body["settings"] = settings
	}

	return body, nil
}

func mergeApplicationUpdateBody(current, update map[string]interface{}) map[string]interface{} {
	allowed := []string{
		"certificate",
		"description",
		"enabled",
		"factors",
		"identityProviders",
		"metadata",
		"name",
		"requiredPermissions",
		"settings",
		"template",
	}
	body := make(map[string]interface{}, len(allowed))
	for _, field := range allowed {
		if value, ok := current[field]; ok {
			body[field] = value
		}
	}
	for field, value := range update {
		body[field] = value
	}
	return body
}

func (r *ApplicationResource) readCredentials(model *ApplicationModel, data map[string]interface{}) {
	if settings, ok := data["settings"].(map[string]interface{}); ok {
		if oauth, ok := settings["oauth"].(map[string]interface{}); ok {
			if clientID, ok := oauth["clientId"].(string); ok {
				model.ClientID = types.StringValue(clientID)
			}
			if clientSecret, ok := oauth["clientSecret"].(string); ok {
				model.ClientSecret = types.StringValue(clientSecret)
			}
		}
	}
}

func (r *ApplicationResource) readIntoModel(model *ApplicationModel, data map[string]interface{}) {
	if id, ok := data["id"].(string); ok {
		model.ID = types.StringValue(id)
	}
	if name, ok := data["name"].(string); ok {
		model.Name = types.StringValue(name)
	}
	if appType, ok := data["type"].(string); ok {
		model.Type = types.StringValue(strings.ToUpper(appType))
	}
	if desc, ok := data["description"].(string); ok {
		model.Description = types.StringValue(desc)
	}

	// Read credentials
	r.readCredentials(model, data)

	// Read identity providers
	if idps, ok := data["identityProviders"].([]interface{}); ok {
		if len(model.IdentityProviderRules) > 0 {
			// Read into structured rules (preserve plan order/values)
			model.IdentityProviderRules = make([]IdentityProviderRuleModel, len(idps))
			for i, idp := range idps {
				if idpMap, ok := idp.(map[string]interface{}); ok {
					rule := IdentityProviderRuleModel{}
					if identity, ok := idpMap["identity"].(string); ok {
						rule.Identity = types.StringValue(identity)
					}
					if selectionRule, ok := idpMap["selectionRule"].(string); ok {
						rule.SelectionRule = types.StringValue(selectionRule)
					} else {
						rule.SelectionRule = types.StringValue("")
					}
					switch p := idpMap["priority"].(type) {
					case float64:
						rule.Priority = types.Int64Value(int64(p))
					case int64:
						rule.Priority = types.Int64Value(p)
					default:
						rule.Priority = types.Int64Value(int64(i))
					}
					model.IdentityProviderRules[i] = rule
				}
			}
			model.IdentityProviders = nil
		} else if len(idps) > 0 {
			// Read into simple list (backward compat), only if non-empty
			model.IdentityProviders = make([]types.String, len(idps))
			for i, idp := range idps {
				if idpMap, ok := idp.(map[string]interface{}); ok {
					if identity, ok := idpMap["identity"].(string); ok {
						model.IdentityProviders[i] = types.StringValue(identity)
					}
				}
			}
		}
	}

	// Read factors
	if factors, ok := data["factors"].([]interface{}); ok {
		model.Factors = make([]types.String, len(factors))
		for i, f := range factors {
			if fStr, ok := f.(string); ok {
				model.Factors[i] = types.StringValue(fStr)
			}
		}
	}

	// Read OAuth settings. If settings_json is configured without the typed
	// block, keep ownership in the raw JSON attribute to avoid synthetic diffs.
	if settings, ok := data["settings"].(map[string]interface{}); ok {
		if oauth, ok := settings["oauth"].(map[string]interface{}); ok &&
			(model.OAuthSettings != nil || model.SettingsJSON.IsNull() || model.SettingsJSON.IsUnknown()) {
			if model.OAuthSettings == nil {
				model.OAuthSettings = &OAuthSettingsModel{}
			}
			if uris, ok := oauth["redirectUris"].([]interface{}); ok {
				model.OAuthSettings.RedirectURIs = toStringSlice(uris)
			}
			if uris, ok := oauth["postLogoutRedirectUris"].([]interface{}); ok {
				model.OAuthSettings.PostLogoutRedirectURIs = toStringSlice(uris)
			}
			if gts, ok := oauth["grantTypes"].([]interface{}); ok {
				model.OAuthSettings.GrantTypes = toStringSlice(gts)
			}
			if rts, ok := oauth["responseTypes"].([]interface{}); ok {
				model.OAuthSettings.ResponseTypes = toStringSlice(rts)
			}
			if scopeSettings, ok := oauth["scopeSettings"].([]interface{}); ok {
				scopes := make([]types.String, 0, len(scopeSettings))
				for _, s := range scopeSettings {
					if sm, ok := s.(map[string]interface{}); ok {
						if scope, ok := sm["scope"].(string); ok {
							scopes = append(scopes, types.StringValue(scope))
						}
					}
				}
				if len(scopes) > 0 {
					model.OAuthSettings.Scopes = scopes
				}
			}
			model.OAuthSettings.AccessTokenValiditySeconds = readOptionalInt64(oauth, "accessTokenValiditySeconds")
			model.OAuthSettings.RefreshTokenValiditySeconds = readOptionalInt64(oauth, "refreshTokenValiditySeconds")
			model.OAuthSettings.IDTokenValiditySeconds = readOptionalInt64(oauth, "idTokenValiditySeconds")
		}

		// Read MFA settings (only if already present in model/plan)
		if mfa, ok := settings["mfa"].(map[string]interface{}); ok && model.MFASettings != nil {
			if enroll, ok := mfa["enroll"].(map[string]interface{}); ok {
				if t, ok := enroll["type"].(string); ok {
					model.MFASettings.Enrollment = types.StringValue(strings.ToUpper(t))
				}
			}
			if challenge, ok := mfa["challenge"].(map[string]interface{}); ok {
				if t, ok := challenge["type"].(string); ok {
					model.MFASettings.Challenge = types.StringValue(strings.ToUpper(t))
				}
			}
		}
	}

	if metadata, ok := data["metadata"].(map[string]interface{}); ok &&
		(!model.MetadataJSON.IsNull() && !model.MetadataJSON.IsUnknown()) {
		metadataJSON, err := json.Marshal(metadata)
		if err == nil {
			model.MetadataJSON = types.StringValue(string(metadataJSON))
		}
	}
}

func metadataJSONToAPI(value types.String) (map[string]interface{}, bool, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, false, nil
	}

	var metadata map[string]interface{}
	if err := json.Unmarshal([]byte(value.ValueString()), &metadata); err != nil {
		return nil, false, fmt.Errorf("metadata_json must be a valid JSON object: %w", err)
	}
	if metadata == nil {
		return nil, false, fmt.Errorf("metadata_json must be a valid JSON object")
	}
	return metadata, true, nil
}

func settingsJSONToAPI(value types.String) (map[string]interface{}, bool, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, false, nil
	}

	var settings map[string]interface{}
	if err := json.Unmarshal([]byte(value.ValueString()), &settings); err != nil {
		return nil, false, fmt.Errorf("settings_json must be a valid JSON object: %w", err)
	}
	if settings == nil {
		return nil, false, fmt.Errorf("settings_json must be a valid JSON object")
	}
	return settings, true, nil
}

func redirectURIsForCreate(plan ApplicationModel) ([]string, error) {
	if plan.OAuthSettings != nil && plan.OAuthSettings.RedirectURIs != nil {
		return toStringSliceFromValues(plan.OAuthSettings.RedirectURIs), nil
	}

	settings, ok, err := settingsJSONToAPI(plan.SettingsJSON)
	if err != nil || !ok {
		return nil, err
	}

	oauth, ok := settings["oauth"].(map[string]interface{})
	if !ok {
		return nil, nil
	}

	redirectURIs, ok := oauth["redirectUris"]
	if !ok {
		return nil, nil
	}

	rawList, ok := redirectURIs.([]interface{})
	if !ok {
		return nil, fmt.Errorf("settings_json.oauth.redirectUris must be a JSON array of strings")
	}
	return jsonStringList(rawList, "settings_json.oauth.redirectUris")
}

func mergeSettingsSection(settings map[string]interface{}, key string, overlay map[string]interface{}) {
	if len(overlay) == 0 {
		return
	}

	existing, ok := settings[key].(map[string]interface{})
	if !ok {
		settings[key] = overlay
		return
	}

	mergeStringInterfaceMap(existing, overlay)
	settings[key] = existing
}

func mergeStringInterfaceMap(dst, src map[string]interface{}) {
	for key, value := range src {
		srcMap, srcIsMap := value.(map[string]interface{})
		dstMap, dstIsMap := dst[key].(map[string]interface{})
		if srcIsMap && dstIsMap {
			mergeStringInterfaceMap(dstMap, srcMap)
			continue
		}
		dst[key] = value
	}
}

func toStringSlice(iface []interface{}) []types.String {
	result := make([]types.String, len(iface))
	for i, v := range iface {
		if s, ok := v.(string); ok {
			result[i] = types.StringValue(s)
		}
	}
	return result
}

func toStringSliceFromValues(values []types.String) []string {
	result := make([]string, len(values))
	for i, value := range values {
		result[i] = value.ValueString()
	}
	return result
}

func jsonStringList(values []interface{}, field string) ([]string, error) {
	result := make([]string, len(values))
	for i, value := range values {
		stringValue, ok := value.(string)
		if !ok {
			return nil, fmt.Errorf("%s must contain only strings", field)
		}
		result[i] = stringValue
	}
	return result, nil
}

func readOptionalInt64(data map[string]interface{}, key string) types.Int64 {
	if v, ok := data[key]; ok {
		switch n := v.(type) {
		case float64:
			return types.Int64Value(int64(n))
		case int64:
			return types.Int64Value(n)
		}
	}
	return types.Int64Null()
}
